### ISSUE TITLE
why host on heroku rather than locally?

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/db-morning-challenge#26]
Just wondering what the purpose is of getting students to setup a new hosted DB instead of just a local one?

**Comment by shiryz** [comment]
The short answer: so they can practice it before the projects.
Long answer: the original challenge would ask students to host the database on elephantSQL so they can type queries in the `browser` tab and that was changed to heroku since students had problems with it https://github.com/foundersandcoders/db-morning-challenge/issues/13.

**Comment by m4v15** [comment]
Re-opening this as we were also confused by this and presumably future mentors also will be - I think maybe adding either a `mentor_notes.md` or a bit at the start of the readme explaining this to the students as well would be good (I'll do this I'm just giving myself a reminder/following process). 

Also having it on heroku means people could pair and access the same DB

**Comment by m4v15** [comment]
I think need an explanation that hosting it on heroku won't actually create an app - we are just doing that to access a database (this confused us slightly at first)

**Comment by shiryz** [comment]
@m4v15 can this be closed now that #36 is merged?
